# Upload Android artifacts
name: Upload Android Github artifacts CD

on:
  repository_dispatch:
    types: [trigger-release]

jobs:
  android-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-artifacts.yml
          workflow_conclusion: success
          name: upcontracts.jar
          path: java/build/libs
          branch: main
          event: push

      - name: Publish jar
        working-directory: ./java
        run: gradle publish
        env:
          # https://github.com/actions/setup-node/issues/49
          # Have to use my personal access token until the issue is resolved
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.PERSONAL_ACTOR }}
